### ISSUE TITLE
Plugin Does Not Work When Installing Inside Godot

### ISSUE THREAD

**Issue by paulhocker** [fenix-hub/godot-engine.text-editor#1]
Very nice plugin, I see some potential to use this quite a bit.

However, the Asset did not install into any addons folder by default and therefore was not included on plugin list after installation.

I had to manually move the file-editor folder to the addons folder to make it work.

This will be very difficult for new people who are not familiar with addons to know how to do this. 

I suggest you include addons folder on your path when you package it.

**Comment by fenix-hub** [comment]
Hi Paul!
Thank you for the feedback and for the mail, very kind and helpful.
I noticed this issue some days ago but never had the time to update the
plugin repository.
This same issue is also present in my second repo
"godot-engine.github-integration" and today I'll update them both with new
versions.
I'm also planning to add new features to the text-editor plugin, so stay
tuned for the new version.
Again, thank you very much, have a good day!

Il giorno lun 23 set 2019 alle ore 07:07 Paul Hocker <
notifications@github.com> ha scritto:
