### ISSUE TITLE
[Feature] Double Click Item in CFG/INI Editor For Editing

### ISSUE THREAD

**Issue by paulhocker** [fenix-hub/godot-engine.text-editor#14]
This is a killer tool. A nice convenience would be to have double click added for editing an existing value. Or better yet, allow editing inside the displayed value like you do for the CSV editor.

Keep up the awesome work.

**Comment by fenix-hub** [comment]
Hi,
Editing a value is already possible within the Editor.
![ae](https://user-images.githubusercontent.com/45271396/79379710-95cbbf00-7f5f-11ea-9075-5af2e7e89d4b.PNG)
1. select the key whose value you want to change
2. press the "edit" button (pencil) and change the value

Do you think that a double click/direct edit method would be better/faster?
I could implement both, and leave the pencil button maybe for something more interesting, like a multi edit feature.

**Comment by paulhocker** [comment]
When I click the edit button, I do not see the existing value in the edit box.

![image](https://user-images.githubusercontent.com/2214652/79396490-aec57780-7f41-11ea-997c-fa2bbb8e90b1.png)

subsequently, adding a new item leaves the last value in the edit box no matter what key you pick

![image](https://user-images.githubusercontent.com/2214652/79396631-f51ad680-7f41-11ea-8f20-245f53bd49b7.png)

i also found some cases where after i edited a value it dissappeared. thankfully it was still in the file.

**Comment by fenix-hub** [comment]
Commit 276cc70dbc68b132520e9afa202dc8a9a1415a31 fixes the issue.
