### ISSUE TITLE
Crashes every other time I open a file

### ISSUE THREAD

**Issue by clownfetus** [fenix-hub/godot-engine.text-editor#19]
Firstly, great work. This is an essential tool and should be included in Godot by default. However, I tested with .txt and .md files made with both the tool and the terminal. Opening a file crashes Godot the first time but running it and trying again works fine. Then if I try to open a different file, same problem. I'm running this on Linux and thanks in advance.

**Comment by fenix-hub** [comment]
Hi @reneishraq ,
Are you able to use an external console to get what is happening when Godot crashes?
The plugin should not make the whole engine crash, but I can check it out if could give me more informations.

**Comment by clownfetus** [comment]
Hey, I didn't end up checking the crash messages. I have already reinstalled my Linux build and it works pretty flawlessly now. Sorry about that.
