### ISSUE TITLE
[Pull Request] Full Markdown support

### ISSUE THREAD

**Issue by nonunknown** [fenix-hub/godot-engine.text-editor#20]
Hi fenix, hope you remember me, I could do a pull request but first I want to know your toughts, As you know (or not) I've made this proposal:

https://github.com/godotengine/godot-proposals/issues/1323

In order to make it possible, a `description.md` file is required, I did know your markdown system, but it doesnt support all markdown features, so I've made it, so if you want to include it on your project I made this issue!

**Before:**

![Screenshot from 2020-08-09 16-15-27](https://user-images.githubusercontent.com/58845030/89739992-aac2e580-da5b-11ea-9c02-7d965c65c8b4.png)

**After:**
![Screenshot from 2020-08-09 16-16-03](https://user-images.githubusercontent.com/58845030/89740004-bdd5b580-da5b-11ea-85e9-a145bde84be2.png)
![Screenshot from 2020-08-09 16-15-58](https://user-images.githubusercontent.com/58845030/89740005-bf06e280-da5b-11ea-955d-92af27721b50.png)
![Screenshot from 2020-08-09 16-15-50](https://user-images.githubusercontent.com/58845030/89740007-bf9f7900-da5b-11ea-869c-8838ed5b23b5.png)

As you can see, it gets online images, stores in a folder, so its one time download, (only support PNG for now)
What it supports now:
* Images
* This list Im typing now
* Explicit urls (click and go to page)
* Non-Explicit urls like [this](www.google.com)
* inline code
* multiline code
* Headers (#) from 1-6
* some minor fixes

If you want the source just tell me!

**Comment by fenix-hub** [comment]
Hi @nonunknown ,
Thank you for this effort.

Make a Pull request whenever you want, I'll review it and if everything is fine I'll merge it to this plugin with no problem whatsoever. 
The source is mandatory since, before merging the pull request, I still need to review it to make sure that everything is fine with the rest of the code.
