### ISSUE TITLE
Changing the Editor Font

### ISSUE THREAD

**Issue by paulhocker** [fenix-hub/godot-engine.text-editor#23]
I currently do not see a way to change the font for the Vanilla text editor? Is there an option somewhere I am missing or is this a missing feature? I would prefer a mono spaced font instead.

Great work on this plugin!

**Comment by fenix-hub** [comment]
Hi @paulhocker ,
If you think it would be a useful feature to have, I'll work on it for sure :)

**Comment by fenix-hub** [comment]
Hi @paulhocker ,
The requested feature is now available. Sorry for keeping you waiting :) 
#24 closes this by adding a new option menu on the top bar of the File Editor.  
Right now it only has a new option, "Change Font", which as the name says will let you select your own personal font for the current opened Vanilla Editor.  
You are free to chose a font from your file system, so you don't need to store the font itself inside your project folder, which will inevitably increase your project folder size.
Also, the font you are using for that specific vanilla editor is stored in the plugin settings, so you won't need to set it again after you close and reopen your Godot project.
For any bug or additional feature, feel free to open other issues or just contact me via Discord :)
Have a nice day

Here some screenshots:
![godot windows opt tools 64_Cj8myEP7x3](https://user-images.githubusercontent.com/45271396/95769839-c6937380-0cb8-11eb-8700-fada5b5a05e2.png)
![Yb68tPPeg7](https://user-images.githubusercontent.com/45271396/95769841-c7c4a080-0cb8-11eb-87d8-b40c2629594d.png)
