### ISSUE TITLE
Enhancement To Font Changing

### ISSUE THREAD

**Issue by paulhocker** [fenix-hub/godot-engine.text-editor#25]
Thank you for making the change to allow changing font. Unfortunately, I do not believe this is the correct way to accomplish this. Instead I think you should get the font from the settings in the Godot editor itself.

For example, I already have my favorite font for the Editor, why would I not have the same?

Is it possible to just grab the font at this setting:

![image](https://user-images.githubusercontent.com/2214652/95817471-2bfe5900-0ce7-11eb-88ea-950aea481437.png)

Thanks again for making the first change.

**Comment by fenix-hub** [comment]
Hi @paulhocker ,
I understood that you just wanted to change the font of the vanilla editor, no mentions about the font you already used in your editor.
No problem, I'll work on it today to fix this :)

**Comment by paulhocker** [comment]
I had not originally thought of that. But then it occurred to me that I already did this in the Godot settings so it is more consistent for your users. Thanks for looking at this.
