### ISSUE TITLE
[BUG] Errors when starting Game related to EditorPlugin

### ISSUE THREAD

**Issue by paulhocker** [fenix-hub/godot-engine.text-editor#28]
**Describe the bug**
When starting a game using the file-editor plugin, an error message shows that is related to the plugin being active. Deactivating the plugin removes the messages. The message is

ERROR: instance: Class 'EditorPlugin' can only be instantiated by editor.
   At: core/class_db.cpp:544
ERROR: Class type: 'EditorPlugin' is not instantiable.
   At: modules/gdscript/gdscript.cpp:70

**To Reproduce**
Activate the plugin and run your game. Observe the errors.
Deactivate the plugin and notice that the message is gone.

**Expected behavior**
There should be no errors when starting the game. It leads the developer to believe there is an error with their game.

**Screenshots**
See error message above.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Godot Engine Version: 3.2.3
- Plugin Version: 1.7.7

**Additional context**
None

**Comment by fenix-hub** [comment]
#30 closes this issue
the EditorPlugin class is not called outside of a function anymore.
Additionaly, the plugin will only load in editor.
