### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by paulhocker** [fenix-hub/godot-engine.text-editor#44]
**Describe the bug**
FE running in Godot 3.3 is producing errors.

**To Reproduce**
1. import FE
2. activate
3. view errors

**Expected behavior**
There should be no errors on startup. 

**Screenshots**

Godot Engine v3.3.stable.official (c) 2007-2021 Juan Linietsky, Ariel Manzur & Godot Contributors.
--- GDScript language server started ---
Add AutoLoad
 scene/resources/texture.cpp:502 - Condition "!f" is true. Returned: ERR_CANT_OPEN
 Failed loading resource: res://.import/msedge_zmozPZZj3p.png-45b22e8e658d9e618635e91966d71bb1.stex. Make sure resources have been imported by opening the project in the editor at least once.
 Failed loading resource: res://addons/file-editor/howto/api_token/msedge_zmozPZZj3p.png. Make sure resources have been imported by opening the project in the editor at least once.
 scene/resources/texture.cpp:502 - Condition "!f" is true. Returned: ERR_CANT_OPEN
 Failed loading resource: res://.import/LR7EGXjHCm.png-1cc143c744f882fbc86edc7d2318e169.stex. Make sure resources have been imported by opening the project in the editor at least once.
 Failed loading resource: res://addons/file-editor/howto/api_token/LR7EGXjHCm.png. Make sure resources have been imported by opening the project in the editor at least once.
Add AutoLoad
Add AutoLoad
 editor/import/resource_importer_csv_translation.cpp:96 - Condition "line.size() <= 1" is true. Returned: ERR_PARSE_ERROR
 editor/editor_file_system.cpp:1817 - Error importing 'res://addons/file-editor/file.samples/sample.csv'.
 editor/import/resource_importer_csv_translation.cpp:96 - Condition "line.size() <= 1" is true. Returned: ERR_PARSE_ERROR
 editor/editor_file_system.cpp:1817 - Error importing 'res://addons/file-editor/file.samples/translation.csv'.
 editor/import/resource_importer_csv_translation.cpp:96 - Condition "line.size() <= 1" is true. Returned: ERR_PARSE_ERROR
 editor/editor_file_system.cpp:1817 - Error importing 'res://addons/file-editor/file.samples/sample.csv'.
 editor/import/resource_importer_csv_translation.cpp:96 - Condition "line.size() <= 1" is true. Returned: ERR_PARSE_ERROR
 editor/editor_file_system.cpp:1817 - Error importing 'res://addons/file-editor/file.samples/translation.csv'.
 editor/import/resource_importer_csv_translation.cpp:96 - Condition "line.size() <= 1" is true. Returned: ERR_PARSE_ERROR
 editor/editor_file_system.cpp:1817 - Error importing 'res://addons/file-editor/file.samples/sample.csv'.
 editor/import/resource_importer_csv_translation.cpp:96 - Condition "line.size() <= 1" is true. Returned: ERR_PARSE_ERROR
 editor/editor_file_system.cpp:1817 - Error importing 'res://addons/file-editor/file.samples/translation.csv'.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Godot Engine Version 3.3
- Plugin Version master

**Additional context**

**Comment by fenix-hub** [comment]
Hi @paulhocker ,
I've not already tested this plugin on 3.3.
I'll do it as soon as possible. THanks

**Comment by fenix-hub** [comment]
Should be fixed by #45
